@Pixoo16Lib_HostAddress = https://localhost:7277

GET {{Pixoo16Lib_HostAddress}}/api/divoom/devices

###


POST {{Pixoo16Lib_HostAddress}}/api/divoomcontroller2/send-gif

###


POST {{Pixoo16Lib_HostAddress}}/api/divoom/send-gif

{
    Allow;
}
###

GET {{Pixoo16Lib_HostAddress}}/api/divoom/send-gif

###

GET {{Pixoo16Lib_HostAddress}}/api/divoom/send-gifRed

###
