@Pixoo16Lib_HostAddress = https://localhost:7277

GET {{Pixoo16Lib_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Pixoo16Lib_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###

GET {{Pixoo16Lib_HostAddress}}/api/todoitems

###

@id=1
GET {{Pixoo16Lib_HostAddress}}/api/todoitems/{{id}}

###

PUT {{Pixoo16Lib_HostAddress}}/api/todoitems/1
Content-Type: application/json

{
  "id": 1,
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{Pixoo16Lib_HostAddress}}/api/todoitems/1

###

GET {{Pixoo16Lib_HostAddress}}/api/divoom/devices

###


POST {{Pixoo16Lib_HostAddress}}/api/divoomcontroller2/send-gif

###


POST {{Pixoo16Lib_HostAddress}}/api/divoom/send-gif

{
    Allow;
}
###

GET {{Pixoo16Lib_HostAddress}}/api/divoom/send-gif

###

GET {{Pixoo16Lib_HostAddress}}/api/divoom/send-gifRed

###

POST {{Pixoo16Lib_HostAddress}}/pixoo/play-sound

###
